name: Trigger auto deployment for avans-keuzecompass

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/avans-keuzecompass-AutoDeployTrigger-65c05818-d586-473e-80fd-75b4b82e5cf4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AVANSKEUZECOMPASS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AVANSKEUZECOMPASS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AVANSKEUZECOMPASS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: avanskeuzecompass.azurecr.io
          registryUsername: ${{ secrets.AVANSKEUZECOMPASS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AVANSKEUZECOMPASS_REGISTRY_PASSWORD }}
          containerAppName: avans-keuzecompass
          resourceGroup: fulstackjavascript
          imageToBuild: avanskeuzecompass.azurecr.io/avans-keuzecompass:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


